---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: discord-bot
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "discord-bot.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - discord-bot
  http:
  - route:
    - destination:
        host: discord-bot-svc
        port:
          number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: discord-bot
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "discord-bot.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: discord-bot
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: port5000
  selector:
    app: discord-bot
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: discord-bot
  name: discord-bot
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
          name: port5005
        env:
        - name: VC_URL
          value: "http://vc.bloxinfra.com/api/monitor" 
        
        - name: VC_STAGE_URL
          value: "http://vc.stage.bloxinfra.com/api/monitor"

        - name: PORT
          value: "5005"

        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: token

        - name: DEV_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: dev_channel_id

        - name: ALL_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: all_channel_id
