---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: discord-bot
  name: discord-bot
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["/bin/sh", "-c", "yarn start"]
        env:
        - name: VC_URL
          value: "http://vc.bloxinfra.com/api/monitor" 
        
        - name: VC_STAGE_URL
          value: "http://vc.stage.bloxinfra.com/api/monitor"

        - name: PORT
          value: "5000"

        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: token

        - name: DEV_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: dev_channel_id
