version: '3.5'

networks:
  main:
    external:
      name: main
  default:
    name: main

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/app/
    ports:
      - "$PORT:$PORT"
    environment:
      - ENV
      - PORT
      - TOKEN
      - VC_URL
      - ORG_URL
      - BLOXCHA_PYRMONT_URL
      - BLOXCHA_MAINNET_URL
      - CHANNEL_ID
      - PGUSER
      - PGHOST
      - PGPASSWORD
      - PGDATABASE_PYRMONT
      - PGDATABASE_MAINNET

    restart: on-failure