version: '3.5'

networks:
  main:
    external:
      name: main
  default:
    name: main

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/app/
    ports:
      - "$PORT:$PORT"
    environment:
      - ENV
      - PORT
      - TOKEN
      - VC_URL
      - ORG_URL
      - ALL_CHANNEL_ID
      - DEV_CHANNEL_ID
      - E2M_PRATER_URL
      - E2M_MAINNET_URL
    restart: on-failure
